### ISSUE TITLE
Exception Occurred (Tokens view)

### ISSUE THREAD

**Issue by niko-kv** [UE-Explorer/UE-Explorer#46]
Hey!

Bugs seems continue their resistance
There is "Exception Occurred" window appears, when you click on:
  "View" > "View Tokens"
  "View" > "View Disassembled Tokens"

```
Thrown by:WinIOError
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at UEExplorer.UI.Tabs.UC_PackageExplorer.PerformNodeAction(Object target, String action)
```
`Could not find a part of the path 'D:\Program Files (x86)\EliotVU\UE Explorer\Templates\struct.tokens.txt'.`
`Could not find file 'D:\Program Files (x86)\EliotVU\UE Explorer\Templates\struct.tokens-disassembled.txt'.`

P.S.: I just checked v1.3.2 and both work without any issues.

**Comment by EliotVU** [comment]
Moving the content from `C:\Program Files (x86)\EliotVU\UE Explorer\Config\Templates` to `C:\Program Files (x86)\EliotVU\UE Explorer\Templates` seems to fix it.
