### ISSUE TITLE
(Rocket League - Error) - exception when trying to load decrypted ProjectX.upk

### ISSUE THREAD

**Issue by WannabeModder** [UE-Explorer/UE-Explorer#54]
I saw that this tool somewhat supports Rocket League so I decided to try it. I used your UPK decrypt tool for RL before trying to load into UE Explorer but had no success.

I did some digging and it's generating an exception while trying to deserialize Exports. Here's a screenshot of where the exception is generated:
![image](https://github.com/UE-Explorer/UE-Explorer/assets/167991734/a10c191f-d2dc-400f-a832-33e3dcfa5816)

Right after this call after trying to read ClassIndex at `_ClassIndex = stream.ReadObjectIndex();` it generates this exception.

Do you have any insights on how to resolve this? I don't have much experience with UPK so I'm kinda lost. I appreciate any help, thank you!

EDIT1: Forgot to attach exception dump
EDIT2: Looks like it happens to any decrypted UPKs.
```
Thrown by:InitializeFromFile
   at UEExplorer.UI.Tabs.UC_PackageExplorer.InitializeFromFile(String filePath)
   at System.Windows.Forms.UserControl.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.ControlCollection.Add(Control value)
   at UEExplorer.UI.ProgramForm.LoadFromFile(String filePath)UELib.UnrealException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at UELib.UExportTableItem.Deserialize(IUnrealStream stream)
   at UELib.UnrealPackage.Deserialize(UPackageStream stream)
   at UELib.UnrealLoader.LoadPackage(String packagePath, BuildName buildTarget, FileAccess fileAccess)
   at UEExplorer.UI.Tabs.UC_PackageExplorer.LoadPackage()
   --- End of inner exception stack trace ---
   at UEExplorer.UI.Tabs.UC_PackageExplorer.LoadPackage()
   at UEExplorer.UI.Tabs.UC_PackageExplorer.InitializeFromFile(String filePath)
   ```

**Comment by EliotVU** [comment]
I have not been keeping up with all the changes RL has gone through, perhaps the latest version simply no longer works? Nonetheless, I think I may have found the culprit, but I'm unable to test this out myself, as I don't have a copy of the latest files.

**Comment by WannabeModder** [comment]
I tried the change and it's a progress! However, functions are failing to decompile. Some examples here:
![image](https://github.com/UE-Explorer/UE-Explorer/assets/167991734/28af98c2-40c1-4a71-b96f-133b122d7091)

Btw: I can attach the file if you want to. Thanks for your support so far!

**Comment by EliotVU** [comment]
Nice. And yes, I would appreciate it!

**Comment by WannabeModder** [comment]
Here it is:
[UPK.zip](https://github.com/UE-Explorer/UE-Explorer/files/15101595/UPK.zip)

I included both the original and decrypted files. These are the ones I've been targeting

**Comment by EliotVU** [comment]
Thanks. It looks like they shifted ALL the byte codes around, pretty much like AA2 did 🤣

![image](https://github.com/UE-Explorer/UE-Explorer/assets/808593/a717c7b7-6c93-4645-8e3c-23b1c991e643)

I've fixed the deserialization for all classes, except for the shifted byte codes, this is a bit of a tedious process.

**Comment by WannabeModder** [comment]
Thanks!! Is there any way I can check the bytecodes myself? Or I'll have to reverse the game binary to check them?

**Comment by EliotVU** [comment]
Yes, I recommend Ghidra to analyze the binary, then search in memory for the unicode string "bad expr", this will lead you to the `SerializeExpr` function, in this function there is a switch on all byte-codes.

**Comment by WannabeModder** [comment]
Does it have support for QwordZero? I tried searching for it in the source of UELib but I couldn't find anything. This is clearly a Qword/PointerZero handler: 
![image](https://github.com/UE-Explorer/UE-Explorer/assets/167991734/3c76d4c2-7de1-4d10-a37b-7691f6479bfb)

**Comment by EliotVU** [comment]
No, I don't think you are looking at the right place.

It should look like this:

![GIF 25-04-2024 22-05-21](https://github.com/UE-Explorer/UE-Explorer/assets/808593/55ab379d-b0a5-47fd-9bff-64df88899a34)
