### ISSUE TITLE
Issues opening files from MotherGunShip: Forge

### ISSUE THREAD

**Issue by Developer-Maker-Educator** [UE-Explorer/UE-Explorer#59]
HI there, love the software! Used it a bunch working on mods for XCOM. I'm having issues opening files in the game MOTHERGUNSHIP: FORGE, a VR game I'm playing through Steam. Happy to send over files to help debug this issue.

### Issue
If I try to open the main game .pak or any extracted .uexp files (using the method described below) in UE Explorer, I get a message saying, "This package has an unknown signature. Are you sure you want to deserialize this package? Clicking Yes might lead to unexpected results!" Selecting No gives no results. Selecting Yes leads to an Exception Occurred message, which I will submit and link to this issue. If I try to open one of the extracted .uasset files, UEE instead freezes with no error messages or end. I have to end it through Task Manager.

### Theory
My theory is that the issues are caused by the game using a vendor-provided version of UE. There used to be an Oculus-provided version of UE on GitHub: https://github.com/Oculus-VR/UnrealEditor -- unfortunately this repo seems to have been taken down. In the properties of the main game .exe, it lists the File Version as 4.27.2.0, and the Product Version as ++UE4+Partner-Oculus-4.27-CL-0.

### Tools Used
I used both the UnrealPak provided by UE 4.27 as well as a version someone posted on GitHub (sorry, can't find the link!), both have the same results in UE Explorer. I can view the .uasset files in AssetEditor (https://github.com/kaiheilos/Utilities) as well as UAssetGUI (https://github.com/atenfyr/UAssetGUI), so I know they're viewable in other programs.

**Comment by Developer-Maker-Educator** [comment]
When I try to submit a report via the Exception handling tool within UE Explorer, I get a "failed to send report!" message. Here's the text of the Exception report:

```
Thrown by:InitializeFromFile
   at UEExplorer.UI.Tabs.UC_PackageExplorer.InitializeFromFile(String filePath)
   at System.Windows.Forms.UserControl.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.ControlCollection.Add(Control value)
   at UEExplorer.UI.ProgramForm.LoadFromFile(String filePath)UELib.UnrealException: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at UELib.UImportTableItem.Deserialize(IUnrealStream stream)
   at UELib.UnrealPackage.Deserialize(UPackageStream stream)
   at UELib.UnrealLoader.LoadPackage(String packagePath, BuildName buildTarget, FileAccess fileAccess)
   at UEExplorer.UI.Tabs.UC_PackageExplorer.LoadPackage()
   --- End of inner exception stack trace ---
   at UEExplorer.UI.Tabs.UC_PackageExplorer.LoadPackage()
   at UEExplorer.UI.Tabs.UC_PackageExplorer.InitializeFromFile(String filePath)
```

**Comment by EliotVU** [comment]
Glad you've find UE Explorer useful, but! UE Explorer does not support any UE4 or UE5 games as of yet, as noted in the README `UE2X and UE4/5 have not been supported as of yet.`

Some *older* .uasset (extracted) do work, but I wouldn't bet on it.

**Comment by Developer-Maker-Educator** [comment]
Oh oops! My bad. I had totally imagined that you supported UE4. Apologies!
